server:
  port: 8080
spring:
  datasource:
    username:
    password:
    url: jdbc:mysql://localhost:3306/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /api-docs
swagger-ui:
  path: /swagger-ui.html